-- Update package prices for all specialists based on the provided list
UPDATE public.specialists SET package_price = 2998 WHERE name = 'AYFER AYDIN';
UPDATE public.specialists SET package_price = 1798 WHERE name = 'Nur Aslan';
UPDATE public.specialists SET package_price = 1020 WHERE name = 'Nilgün Turhan';
UPDATE public.specialists SET package_price = 2398 WHERE name = 'Büşra Demir';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Mürüvet Kara';
UPDATE public.specialists SET package_price = 2398 WHERE name = 'Ayşe Dölek Kerbel';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Fadime Acar';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Şeyda Aras';
UPDATE public.specialists SET package_price = 1500 WHERE name = 'Psk. Beyza Yarar';
UPDATE public.specialists SET package_price = 1998 WHERE name = 'Ayşe Akçayol';
UPDATE public.specialists SET package_price = 1500 WHERE name = 'Şeyda Pınar';
UPDATE public.specialists SET package_price = 3600 WHERE name = 'Firdevs Karaman';
UPDATE public.specialists SET package_price = 1020 WHERE name = 'Fatma Güngören';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Bilal Hatipoğlu';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Ayşe Vural';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Sibel Acar';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Filiz Akman';
UPDATE public.specialists SET package_price = 2398 WHERE name = 'Murat Ekin';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Ayşe Şenocak';
UPDATE public.specialists SET package_price = 3998 WHERE name = 'Ahu Özmen Akalın';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Zeynep Çetin';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Zehra Nur Kör';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Arzu Uysal';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Didem Aydın';
UPDATE public.specialists SET package_price = 2398 WHERE name = 'Sibel Tosuner';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Elif Camcı Kaya';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Yıldız Günel';
UPDATE public.specialists SET package_price = 1998 WHERE name = 'Fatma Çiftçi';
UPDATE public.specialists SET package_price = 1798 WHERE name = 'Öykü Turhan';
UPDATE public.specialists SET package_price = 3600 WHERE name = 'Tanya Şimşir';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Elif Polat';
UPDATE public.specialists SET package_price = 2398 WHERE name = 'Rümeysa Varlı';
UPDATE public.specialists SET package_price = 3600 WHERE name = 'Lefke Tezcan';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Besra Bayram';
UPDATE public.specialists SET package_price = 1998 WHERE name = 'Mihriban Baydeniz';
UPDATE public.specialists SET package_price = 2398 WHERE name = 'Birgül Oktay';
UPDATE public.specialists SET package_price = 3600 WHERE name = 'Tahibe Derici';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Şenay Esen';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Meryem Hotan';
UPDATE public.specialists SET package_price = 3600 WHERE name = 'Zeynep Aydın';
UPDATE public.specialists SET package_price = 2398 WHERE name = 'Kübra Köroğlu Yılmaz';
UPDATE public.specialists SET package_price = 3600 WHERE name = 'Deniz Şanal';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Gökçe Uruk';
UPDATE public.specialists SET package_price = 2398 WHERE name = 'Nurdan Yurdusever';
UPDATE public.specialists SET package_price = 3600 WHERE name = 'Ceylin Kahya';
UPDATE public.specialists SET package_price = 3600 WHERE name = 'Hüseyin Burak Coşkun';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Yeliz Şenyuva';
UPDATE public.specialists SET package_price = 3600 WHERE name = 'Gülizar Göl';
UPDATE public.specialists SET package_price = 3600 WHERE name = 'Emirhan Karaduman';
UPDATE public.specialists SET package_price = 3600 WHERE name = 'Şevval Gökşin Pişkin';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Derya akgüç';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Deniz Sadi';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Şeyma Keleş';
UPDATE public.specialists SET package_price = 3600 WHERE name = 'Ayça Harmankaya';
UPDATE public.specialists SET package_price = 2398 WHERE name = 'Kadriye Erdoğan';
UPDATE public.specialists SET package_price = 2398 WHERE name = 'Ceren Naz Şimşek';
UPDATE public.specialists SET package_price = 2398 WHERE name = 'Özge Larçin';
UPDATE public.specialists SET package_price = 3600 WHERE name = 'Handan Kutlusoy Vural';
UPDATE public.specialists SET package_price = 3600 WHERE name = 'Sinem Erusta';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Beyza Ünal';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Veysel Hasan Gül';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Ayşe Tetik';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Yağmur Çelik';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Ebru Özcan';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Nida nur çetin';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Sibel Kirezci';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Erkan Arıkan';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Şule Uludağ';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Su Ayhan';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Süleyman Ayhan Örnek';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Çağla Çelimli';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Burak Ala';
UPDATE public.specialists SET package_price = 2398 WHERE name = 'Gülbahar Bumin';
UPDATE public.specialists SET package_price = 2398 WHERE name = 'Melike Ermumcu';
UPDATE public.specialists SET package_price = 3600 WHERE name = 'Ayfer Hatipoğlu';
UPDATE public.specialists SET package_price = 2398 WHERE name = 'Ahmet Topaloğlu';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Nehir Yılmaz Ateş';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Havvanur Muradoğlu İncekara';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Tuğba Hasaltın';
UPDATE public.specialists SET package_price = 2398 WHERE name = 'Oya Kayır';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Ayşegül Keskin Çetin';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Sevinç Yeşilyurt';
UPDATE public.specialists SET package_price = 2398 WHERE name = 'Suzan Onur';
UPDATE public.specialists SET package_price = 2398 WHERE name = 'Muhammet Memişoğlu';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Ruken Esen';
UPDATE public.specialists SET package_price = 2398 WHERE name = 'Gürkan Çelik';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Sara Tekin';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Neşe Uslu';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Merve Nur Akçan';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Züleyha Eker';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Gülşen Gürbüz';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Sonay Dayı';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Sevinç Kanat';
UPDATE public.specialists SET package_price = 2998 WHERE name = 'Onur Çankaya';
UPDATE public.specialists SET package_price = 3600 WHERE name = 'Pınar Kurtulan';
UPDATE public.specialists SET package_price = 2398 WHERE name = 'Deniz Deveci';
UPDATE public.specialists SET package_price = 2398 WHERE name = 'Meryem Nur Işık';